/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as EliteHubRouteImport } from './routes/elite-hub'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackingIndexRouteImport } from './routes/tracking.index'
import { Route as TrackingIdRouteImport } from './routes/tracking.$id'
import { Route as ScanIdRouteImport } from './routes/scan.$id'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PaymentCancelRouteImport } from './routes/payment.cancel'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteHubRoute = EliteHubRouteImport.update({
  id: '/elite-hub',
  path: '/elite-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingIndexRoute = TrackingIndexRouteImport.update({
  id: '/tracking/',
  path: '/tracking/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingIdRoute = TrackingIdRouteImport.update({
  id: '/tracking/$id',
  path: '/tracking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIdRoute = ScanIdRouteImport.update({
  id: '/scan/$id',
  path: '/scan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-keys': typeof ApiKeysRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/elite-hub': typeof EliteHubRoute
  '/generator': typeof GeneratorRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/scan/$id': typeof ScanIdRoute
  '/tracking/$id': typeof TrackingIdRoute
  '/tracking/': typeof TrackingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-keys': typeof ApiKeysRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/elite-hub': typeof EliteHubRoute
  '/generator': typeof GeneratorRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/scan/$id': typeof ScanIdRoute
  '/tracking/$id': typeof TrackingIdRoute
  '/tracking': typeof TrackingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-keys': typeof ApiKeysRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/elite-hub': typeof EliteHubRoute
  '/generator': typeof GeneratorRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/scan/$id': typeof ScanIdRoute
  '/tracking/$id': typeof TrackingIdRoute
  '/tracking/': typeof TrackingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-keys'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/elite-hub'
    | '/generator'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/settings'
    | '/terms'
    | '/wallet'
    | '/payment/cancel'
    | '/payment/success'
    | '/scan/$id'
    | '/tracking/$id'
    | '/tracking/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api-keys'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/elite-hub'
    | '/generator'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/settings'
    | '/terms'
    | '/wallet'
    | '/payment/cancel'
    | '/payment/success'
    | '/scan/$id'
    | '/tracking/$id'
    | '/tracking'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-keys'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/elite-hub'
    | '/generator'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/settings'
    | '/terms'
    | '/wallet'
    | '/payment/cancel'
    | '/payment/success'
    | '/scan/$id'
    | '/tracking/$id'
    | '/tracking/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  EliteHubRoute: typeof EliteHubRoute
  GeneratorRoute: typeof GeneratorRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ScanIdRoute: typeof ScanIdRoute
  TrackingIdRoute: typeof TrackingIdRoute
  TrackingIndexRoute: typeof TrackingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite-hub': {
      id: '/elite-hub'
      path: '/elite-hub'
      fullPath: '/elite-hub'
      preLoaderRoute: typeof EliteHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/': {
      id: '/tracking/'
      path: '/tracking'
      fullPath: '/tracking/'
      preLoaderRoute: typeof TrackingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/$id': {
      id: '/tracking/$id'
      path: '/tracking/$id'
      fullPath: '/tracking/$id'
      preLoaderRoute: typeof TrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$id': {
      id: '/scan/$id'
      path: '/scan/$id'
      fullPath: '/scan/$id'
      preLoaderRoute: typeof ScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiKeysRoute: ApiKeysRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  EliteHubRoute: EliteHubRoute,
  GeneratorRoute: GeneratorRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ScanIdRoute: ScanIdRoute,
  TrackingIdRoute: TrackingIdRoute,
  TrackingIndexRoute: TrackingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
